version: "3.9"

services:
  database:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_DB=takehome_ws_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web-service:
    depends_on:
      database:
        condition: service_healthy
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./ws_data:/ws_data
