version: "3.9"

services:
  client:
    build: .
    command: bash -c "pip install requests ; python /client_data/query_api.py"
    volumes:
      - .:/client_data

networks:
    default:
      external:
        name: external-network