# Generated by Django 3.1.5 on 2021-01-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city_name', models.TextField()),
                ('country_name', models.TextField()),
                ('avg_temp', models.FloatField(blank=True, null=True)),
                ('temp_uncertainty', models.FloatField(blank=True, null=True)),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
            ],
            options={
                'db_table': 'land_temperature',
                'ordering': ['date'],
                'managed': True,
            },
        ),
    ]
